/**
 * PDF Exporter for Staff Attendance Tracker
 * Generates exact matching multi-page PDF reports with Red highlights for short hours.
 */

export function generateAttendancePDF(processedRecords, metrics, reportDate = new Date().toLocaleDateString('en-GB')) {
  if (!window.jspdf || !window.jspdf.jsPDF) {
    alert("PDF library is loading. Please try again in a moment.");
    return;
  }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'pt',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const shiftLabel = metrics.targetHoursLabel || '9.5 Hours';

  // Header Banner
  doc.setFillColor(30, 41, 59); // Slate-800
  doc.rect(0, 0, pageWidth, 54, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text("DAILY STAFF ATTENDANCE REPORT", 30, 32);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${reportDate}  |  Target Shift: ${shiftLabel}  |  Lunch: 1.0 Hour`, pageWidth - 30, 32, { align: 'right' });

  // Summary Metrics Bar
  doc.setFillColor(241, 245, 249); // Slate-100
  doc.rect(30, 64, pageWidth - 60, 32, 'F');
  doc.setDrawColor(203, 213, 225);
  doc.rect(30, 64, pageWidth - 60, 32, 'S');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  
  const lateInText = typeof metrics.lateInCount === 'number' ? `   |   Late IN: ${metrics.lateInCount}` : '';
  const metricText = `Total Staff: ${metrics.totalStaff}   |   Present: ${metrics.presentCount}   |   Absent: ${metrics.absentCount}${lateInText}   |   Shortfall (<${shiftLabel}) / Missing: ${metrics.shortfallCount} (RED)   |   Avg Working Hours: ${metrics.avgWorkingHours}`;
  doc.text(metricText, pageWidth / 2, 84, { align: 'center' });

  // Prepare table headers and body
  const tableHeaders = [
    ["SL NO", "NAME", "IN", "1st Out", "1st In", "2nd Out", "2nd In", "3rd Out", "3rd In", "Final Out", "Total Working Hours", "Shortfall", "Remarks"]
  ];

  const tableData = processedRecords.map((r, index) => [
    r.slNo || (index + 1),
    r.name || '',
    r.in || '',
    r.out1 || '',
    r.in1 || '',
    r.out2 || '',
    r.in2 || '',
    r.out3 || '',
    r.in3 || '',
    r.finalOut || '',
    r.totalWorkingHours || '',
    r.shortfall || '',
    r.remarks || ''
  ]);

  // AutoTable configuration
  doc.autoTable({
    head: tableHeaders,
    body: tableData,
    startY: 106,
    margin: { left: 30, right: 30, bottom: 40 },
    theme: 'grid',
    styles: {
      fontSize: 8,
      cellPadding: 4,
      halign: 'center',
      valign: 'middle',
      font: 'helvetica',
      textColor: [30, 41, 59],
      lineColor: [203, 213, 225],
      lineWidth: 0.5
    },
    headStyles: {
      fillColor: [226, 232, 240], // Light Gray Header
      textColor: [15, 23, 42],
      fontStyle: 'bold',
      halign: 'center'
    },
    columnStyles: {
      0: { cellWidth: 30, halign: 'center', fontStyle: 'bold' }, // SL NO
      1: { cellWidth: 105, halign: 'left', fontStyle: 'bold' },  // NAME
      2: { cellWidth: 42 },  // IN
      3: { cellWidth: 55 },  // 1st Out
      4: { cellWidth: 55 },  // 1st In
      5: { cellWidth: 55 },  // 2nd Out
      6: { cellWidth: 55 },  // 2nd In
      7: { cellWidth: 55 },  // 3rd Out
      8: { cellWidth: 55 },  // 3rd In
      9: { cellWidth: 58 },  // Final Out
      10: { cellWidth: 70, fontStyle: 'bold' }, // Total Working Hours
      11: { cellWidth: 55, fontStyle: 'bold' }, // Shortfall
      12: { cellWidth: 'auto' }  // Remarks
    },
    didParseCell: function (data) {
      if (data.section === 'body') {
        const record = processedRecords[data.row.index];
        if (record) {
          if (record.isShortfall) {
            // RED Highlighting for staff working less than target shift or NOTPUNCHED
            data.cell.styles.fillColor = [254, 226, 226]; // Soft red (#fee2e2)
            data.cell.styles.textColor = [153, 27, 27];   // Dark Red text
            if (data.column.index === 10 || data.column.index === 11) {
              data.cell.styles.fontStyle = 'bold';
            }
          }
        }
      }
    },
    didDrawPage: function (data) {
      // Page footer
      const pageNumber = data.pageNumber;
      const str = `Page ${pageNumber}`;
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(148, 163, 184);
      doc.text(str, pageWidth - 30, pageHeight - 15, { align: 'right' });
      doc.text("Generated by Staff Attendance Tracker • Confidential", 30, pageHeight - 15);
    }
  });

  // Save the generated PDF
  const filename = `Attendance_Report_${reportDate.replace(/[\/\\]/g, '-')}.pdf`;
  doc.save(filename);
  return filename;
}
